spring.application.name=gympro

# MongoDB Connection
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://maxiplataformas_db_user:meWrBft8bEvbQLwW@cluster0.blcypj2.mongodb.net/gympro?retryWrites=true&w=majority&appName=Cluster0&tlsInsecure=true}

# Servidor en el puerto 8080 (por defecto)
server.port=8080

# Para ver los logs de Mongo y debug si es necesario
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# Gemini API Key
gemini.api.key=${GEMINI_API_KEY:}

# Email Proxy via Google Apps Script (Free)
google.script.url=https://script.google.com/macros/s/AKfycbz_42IVvpHJ2Bw2P34BLUChCXwIf2yiqd-uPb3YWVThY4CCesmEnNsWy0xrX-xGYJ7Xvg/exec
